apiVersion: v1
kind: Service
metadata:
  name: apache2-service
spec:
  type: NodePort
  selector:
    app: apache2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
    name: apache