# https://eksctl.io/getting-started/
# eksctl create cluster -f cluster.yml
# eksctl delete cluster -f cluster.yml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-app-cluster
  region: us-east-1

nodeGroups:
  - name: nodegroup-1
    instanceType: t3.micro
    desiredCapacity: 3